### PR TITLE
Updated PDFBox to 3.0.3

### PR DESCRIPTION
**Pull request by amatt-riverty**
Updated to latest PDFBox version ([release notes](https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12310760&version=12354416))

### CODE REVIEW

**Comment by finsterwalder** [comment]
Deployed in version 1.2.3

**Comment by amatt-riverty** [comment]
Thank you for your super quick merge!

**Comment by finsterwalder** [comment]
Thank you for your support!

**Comment by amatt-riverty** [comment]
Thank you for your library, awesome!

**Pull request merged**
