### PR TITLE
Java 6+ compatibility

### PR DESCRIPTION
**Pull request by PabloNicolasDiaz**
Java 6+ porting
Integration with lombok

### CODE REVIEW

**Comment by finsterwalder** [comment]
Hello Pablo,

thank you for your work!
Unfortunately I will not merge this request.
I don't want to complicate the project by supporting JDK6.
JDK8 is rather old and I think it's ok to have JDK8 as a requirement.
It's also harder for me to continuously keep up JDK6 compatibility in the long run.
I also don't want to complicate the project with Lombok, which adds another layer one needs to know to work on the project.

Sorry for that!

**Comment by Lonzak** [comment]
Good work! We needed Java 1.7 compatibility, so I can use your version now. Thanks!

**Comment by PabloNicolasDiaz** [comment]
Hello Malte!

Thanks for your feedback and work in pdfcompare!. I was looking a testing framework to test a pdf generator, and your project was the best choice for it. Unfortunately, this generator is targeted for java 1.6 and doing a migration it's not an option beacuse the effort is really big. After thinking about this, I decided to fork it and make a contribution backporting it to Java 1.6 (I have to break your API a little, beacuse some methods used Java 1.8 classes). And, altrought your project can be used for testing the generator, our IDE (Eclipse) can't handle really well multiple java targets in one project. 

I will release this fork in maven central as pdfcompare-jdk6, and I invite you to contribute if you want. Thanks!

**Comment by finsterwalder** [comment]
Hello Pablo,

it's a great idea to publish your jdk6 version as a fork.

Thanks,
   Malte

**Pull request closed without merging**
