### PR TITLE
Upgrade to PDFBox 3.0

### PR DESCRIPTION
**Pull request by stefanhh0**
fixes https://github.com/red6/pdfcompare/issues/131

### CODE REVIEW

**Comment by stefanhh0** [comment]
There is a Test failure: 
IntegrationTest.corruptPdfGivesRenderingException:259 RenderingException expected

**Comment by finsterwalder** [comment]
Thanks!
I also saw that the TestCase fails during my test. PdfBox 3 seams to be much better in handling broken PDFs. ;-)
I think this is not critical and I would remove the test in this case, because I think it's really not critical behaviour.

**Comment by stefanhh0** [comment]
@finsterwalder Thanks for accepting it and for merging!

I have seen you already tagged 1.1.62. When will be the release available in Maven Central and Maven Repository? I need to consume 1.1.62 for a project. It would be awesome to have it available soon.

Best Regards,
Stefan

**Comment by finsterwalder** [comment]
It was submitted to Sonatype Nexus right away.
Tagging and releasing to maven is really just one step (mvn release:prepare release:perform does all of it).
And usually this goes to maven central automatically.
But for some reason it got "stuck" and I had to manually "close" and "release" the staging repository in Nexus.
It is available on Sonatype Nexus right now.
I hope it will be transferred/synced to Maven Central soonish...

**Comment by finsterwalder** [comment]
1.1.62 is available in maven central now.

**Comment by stefanhh0** [comment]
Many Thanks Malte! Perfect!

**Pull request merged**
